name = "SinnioriPinniori Sborka: Fabric Edition"
author = "m_06"
version = "0.9.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ba588619326eca9b3457a7474df8c3704433cdb1ec3fbe77b5c9d67d5e54a865"

[versions]
fabric = "0.16.5"
minecraft = "1.20.1"
