name = "SinnioriPinniori Sborka: Fabric Edition"
author = "m_06"
version = "0.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3237c1e63493205e4c662a486312f01c2ff22787c9b9811398c4a98015ffaf51"

[versions]
fabric = "0.16.5"
minecraft = "1.20.1"
