name = "SinnioriPinniori Sborka: Fabric Edition"
author = "m_06"
version = "1.1.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2974ae3c8d913302ce8ee4e490fde3064dde14857c2d07a7c6ed35da4f7479a2"

[versions]
fabric = "0.16.5"
minecraft = "1.20.1"
