name = "SinnioriPinniori Sborka: Fabric Edition"
author = "m_06"
version = "1.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7e44c6425f678b76b6b7f4129ac853854837eaf0f109d55c263b8d4ffc435b08"

[versions]
fabric = "0.16.5"
minecraft = "1.20.1"
