name = "SinnioriPinniori Sborka: Fabric Edition"
author = "m_06"
version = "0.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "404160a07b5cd688c7ff38baecdbaa9967421d7bd16bba17ad9539a462168287"

[versions]
fabric = "0.16.5"
minecraft = "1.20.1"
