name = "SinnioriPinniori Sborka: Fabric Edition"
author = "m_06"
version = "0.9.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c1751c40d8792bf4ba1dc1d79410190360329083ad12cefcbab8d7056e8ab38f"

[versions]
fabric = "0.16.5"
minecraft = "1.20.1"
