name = "SinnioriPinniori Sborka: Fabric Edition"
author = "m_06"
version = "0.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d212f2be4543199bf61832b51d4a14c0646af9682ba11cbb8198e7d96bea5319"

[versions]
fabric = "0.16.5"
minecraft = "1.20.1"
