name = "SinnioriPinniori Sborka: Fabric Edition"
author = "m_06"
version = "0.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "80c4c1b75fa66008aa6c3fe4c5582d43e8edfc5e21b1bbb00a98c2b5d8697e82"

[versions]
fabric = "0.16.5"
minecraft = "1.20.1"
