name = "SinnioriPinniori Sborka: Fabric Edition"
author = "m_06"
version = "0.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d44852b616ca61bbc8a3222f25560e1352a2b61ff2f915c92a1ab9ea700ae99c"

[versions]
fabric = "0.16.5"
minecraft = "1.20.1"
