name = "SinnioriPinniori Sborka: Fabric Edition"
author = "m_06"
version = "1.0.0-rc2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2ff97ebfd5702b9d6ee361a0af70b786f1b4de0815468bfc7ceb81276b6b5cd0"

[versions]
fabric = "0.16.5"
minecraft = "1.20.1"
