name = "SinnioriPinniori Sborka: Fabric Edition"
author = "m_06"
version = "1.1.20"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d7ed794e7a4b8c24b69cfa1412bdc4bc69465aee0a5185dee2829c0f56fdbac1"

[versions]
fabric = "0.16.5"
minecraft = "1.20.1"
