name = "SinnioriPinniori Sborka: Fabric Edition"
author = "m_06"
version = "1.3.1-the-update-update"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d054eb4e1e615c3c559bcd45aef26ccf24aee9c267351814860613397e22aae2"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
