name = "SinnioriPinniori Sborka: Fabric Edition"
author = "m_06"
version = "0.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "00e830971e359dc5065328adba7419221fef3957aa723b036dfb92757b8f01bc"

[versions]
fabric = "0.16.5"
minecraft = "1.20.1"
