name = "SinnioriPinniori Sborka: Fabric Edition"
author = "m_06"
version = "0.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "06a8e8972930af2db647e0e549134cd1494fa57602620fd2965073fe0b988914"

[versions]
fabric = "0.16.5"
minecraft = "1.20.1"
