name = "SinnioriPinniori Sborka: Fabric Edition"
author = "m_06"
version = "1.0.0-rc3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "07a5968eb6c5430e063823d6de4bbc5f669eff51c7df3041ca4dccefd43da5f0"

[versions]
fabric = "0.16.5"
minecraft = "1.20.1"
