name = "SinnioriPinniori Sborka: Fabric Edition"
author = "m_06"
version = "1.3-the-update"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2e81c76f64f9eca8e383024891f411c840fdd484f484fc119fd49f93dd416985"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
