name = "SinnioriPinniori Sborka: Fabric Edition"
author = "m_06"
version = "0.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c5120de2550450c79b77cc27ac55482bbd43dd573b9e93f65b635c3b6f9efbac"

[versions]
fabric = "0.16.5"
minecraft = "1.20.1"
