name = "SinnioriPinniori Sborka: Fabric Edition"
author = "m_06"
version = "1.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "07dbde483012a4a913171661035640942207509a8a50341d0582c8bf28eb6208"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
