name = "SinnioriPinniori Sborka: Fabric Edition"
author = "m_06"
version = "1.0.0-rc2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2c57be532bf8a77fce6f20484a85695ffe88ff1b1776234424526e2c0491ba5d"

[versions]
fabric = "0.16.5"
minecraft = "1.20.1"
