name = "SinnioriPinniori Sborka: Fabric Edition"
author = "m_06"
version = "0.9.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ad795311acdbc4371e56e033af34c3acbbe480497551a2dd65417eb822ed8cc7"

[versions]
fabric = "0.16.5"
minecraft = "1.20.1"
