name = "SinnioriPinniori Sborka: Fabric Edition"
author = "m_06"
version = "0.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "069ea7f44977827d38e72b5df610424cdd246076185b5f4ee9743a452faabaf7"

[versions]
fabric = "0.16.5"
minecraft = "1.20.1"
