name = "SinnioriPinniori Sborka: Fabric Edition"
author = "m_06"
version = "0.9.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "441b2ef87c24069ece4bf9793608b9895d119b949d3e8565b579257deca3ae2b"

[versions]
fabric = "0.16.5"
minecraft = "1.20.1"
