name = "SinnioriPinniori Sborka: Fabric Edition"
author = "m_06"
version = "0.9.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0a69458e39518757d7217426d9d1eeae8a9eea767aa4f7563041dde2bd3f674b"

[versions]
fabric = "0.16.5"
minecraft = "1.20.1"
