name = "SinnioriPinniori Sborka: Fabric Edition"
author = "m_06"
version = "0.9.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8d9be5fa15bff2421b6ea7d09d678ede002f081e89cfeef4809891ddda603443"

[versions]
fabric = "0.16.5"
minecraft = "1.20.1"
