name = "SinnioriPinniori Sborka: Fabric Edition"
author = "m_06"
version = "1.1.20"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "49344f154eb2841a187906c7b3fbab0b3db923aeb0f5a4ea9dccc06a30994876"

[versions]
fabric = "0.16.5"
minecraft = "1.20.1"
