name = "SinnioriPinniori Sborka: Fabric Edition"
author = "m_06"
version = "1.1.11"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e9904a28832e0f4efe09cc17bebafb894a7fb35c15108f1b0940debc774c42c6"

[versions]
fabric = "0.16.5"
minecraft = "1.20.1"
