name = "SinnioriPinniori Sborka: Fabric Edition"
author = "m_06"
version = "0.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aeef02c8e185d141da9ea078dfecb9b7208aee38f85304bd999908b54902a7dd"

[versions]
fabric = "0.16.5"
minecraft = "1.20.1"
