name = "SinnioriPinniori Sborka: Fabric Edition"
author = "m_06"
version = "1.0.0-rc2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "93caea2c14d4cc02fb5349362c36db3c47c7765e4e6bdc62cd35f7ec140df64d"

[versions]
fabric = "0.16.5"
minecraft = "1.20.1"
