ServerEvents.tags('item', event => {
	event.add('c:stripped_logs', '#forge:stripped_logs')
	event.add('arsenal:big_weapons', 'bewitchment:horned_spear')
	event.add('arsenal:ranged_weapons', 'create:potato_cannon')
	event.add('arsenal:big_weapons', 'create:potato_cannon')
	event.add('arsenal:big_weapons', 'create:extendo_grip')
	event.add('arsenal:displayable', 'create:wrench')
	event.add('arsenal:displayable', 'hexcasting:staff')
	event.add('arsenal:displayable', 'scriptor:bound_sword')
	event.add('arsenal:displayable', 'scriptor:bound_axe')
	event.add('arsenal:displayable', 'scriptor:bound_shovel')
	event.add('arsenal:displayable', 'scriptor:bound_pickaxe')
	event.add('arsenal:displayable', '#c:tools/machetes')
	event.add('arsenal:displayable', '#c:tools/knives')
})
